# Generated by Django 4.2.7 on 2023-11-15 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="comment",
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="date",
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="visit",
            name="doctor",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="link",
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="procedure_details",
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
