# Generated by Django 4.2.7 on 2023-11-15 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_city_name_alter_clinic_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
