# Generated by Django 4.2.7 on 2023-11-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_visit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="comment",
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name="visit",
            name="doctor",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="visit",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="visit",
            name="link",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="visit",
            name="procedure_details",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
