# Generated by Django 4.2.7 on 2023-12-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_visit_comment_alter_visit_doctor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visit",
            options={"ordering": ("-date",)},
        ),
        migrations.RenameField(
            model_name="treatment",
            old_name="date",
            new_name="date_start",
        ),
        migrations.AddField(
            model_name="treatment",
            name="days",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="treatment",
            name="receipt",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="treatment",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
