"""add_body_region_to_visits_and_treatments

Revision ID: 1208caf2fc05
Revises: d1e3633a19c0
Create Date: 2026-03-30 22:42:01.622691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1208caf2fc05'
down_revision: Union[str, Sequence[str], None] = 'd1e3633a19c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment', sa.Column('body_region', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_treatment_body_region'), 'treatment', ['body_region'], unique=False)
    op.add_column('visit', sa.Column('body_region', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_visit_body_region'), 'visit', ['body_region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_body_region'), table_name='visit')
    op.drop_column('visit', 'body_region')
    op.drop_index(op.f('ix_treatment_body_region'), table_name='treatment')
    op.drop_column('treatment', 'body_region')
    # ### end Alembic commands ###
