"""add_profile_fields_to_user

Revision ID: 7fecefec76b8
Revises: 1208caf2fc05
Create Date: 2026-03-31 17:44:52.920643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fecefec76b8'
down_revision: Union[str, Sequence[str], None] = '1208caf2fc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.String(length=10), server_default='male', nullable=False))
    op.add_column('user', sa.Column('date_of_birth', sa.Date(), server_default='1997-07-29', nullable=False))
    op.add_column('user', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('user', sa.Column('blood_type', sa.String(length=5), nullable=True))
    op.add_column('user', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('chronic_conditions', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('emergency_contact_name', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'emergency_contact_phone')
    op.drop_column('user', 'emergency_contact_name')
    op.drop_column('user', 'chronic_conditions')
    op.drop_column('user', 'allergies')
    op.drop_column('user', 'blood_type')
    op.drop_column('user', 'weight_kg')
    op.drop_column('user', 'height_cm')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###
