"""add notification dismissals table

Revision ID: 800ae8943ec0
Revises: ecf6b01bf819
Create Date: 2026-04-07 16:44:21.730286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800ae8943ec0'
down_revision: Union[str, Sequence[str], None] = 'ecf6b01bf819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_dismissal',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('reminder_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', 'reminder_type', name='uq_dismissal')
    )
    op.create_index(op.f('ix_notification_dismissal_user_id'), 'notification_dismissal', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_dismissal_user_id'), table_name='notification_dismissal')
    op.drop_table('notification_dismissal')
    # ### end Alembic commands ###
