"""initial schema

Revision ID: d1e3633a19c0
Revises: 
Create Date: 2026-03-30 18:40:14.000951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e3633a19c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clinic',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('position',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('procedure',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('treatment',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('receipt', sa.String(length=1024), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_treatment_user_id', 'treatment', ['user_id'], unique=False)
    op.create_table('visit',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('doctor', sa.String(length=256), nullable=True),
    sa.Column('procedure_id', sa.BigInteger(), nullable=True),
    sa.Column('procedure_details', sa.String(length=1024), nullable=True),
    sa.Column('clinic_id', sa.BigInteger(), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('document', sa.String(length=512), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visit_date', 'visit', ['date'], unique=False)
    op.create_index('ix_visit_user_date', 'visit', ['user_id', 'date'], unique=False)
    op.create_index('ix_visit_user_id', 'visit', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visit_user_id', table_name='visit')
    op.drop_index('ix_visit_user_date', table_name='visit')
    op.drop_index('ix_visit_date', table_name='visit')
    op.drop_table('visit')
    op.drop_index('ix_treatment_user_id', table_name='treatment')
    op.drop_table('treatment')
    op.drop_table('user')
    op.drop_table('procedure')
    op.drop_table('position')
    op.drop_table('clinic')
    op.drop_table('city')
    # ### end Alembic commands ###
