"""add_weather_city_to_user

Revision ID: ecf6b01bf819
Revises: 712bf519c728
Create Date: 2026-04-05 22:14:59.196700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf6b01bf819'
down_revision: Union[str, Sequence[str], None] = '712bf519c728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weather_city', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('weather_city_auto', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weather_city_auto')
    op.drop_column('user', 'weather_city')
    # ### end Alembic commands ###
