from __future__ import annotations

import builtins
from datetime import datetime
from typing import Optional, Protocol

from app.domain.entities import Visit, Treatment, User, Reference


class VisitRepository(Protocol):
    async def get_by_id(self, visit_id: int, user_id: int) -> Optional[Visit]: ...
    async def list(self, user_id: int, filters: dict, sort: str, page: int, size: int) -> tuple[builtins.list[Visit], int]: ...
    async def save(self, visit: Visit) -> Visit: ...
    async def count_total(self, user_id: int) -> int: ...
    async def list_recent(self, user_id: int, limit: int = 10) -> builtins.list[Visit]: ...


class TreatmentRepository(Protocol):
    async def get_by_id(self, treatment_id: int, user_id: int) -> Optional[Treatment]: ...
    async def list_all(self, user_id: int) -> list[Treatment]: ...
    async def save(self, treatment: Treatment) -> Treatment: ...


class UserRepository(Protocol):
    async def get_by_id(self, user_id: int) -> Optional[User]: ...
    async def get_by_username(self, username: str) -> Optional[User]: ...


class ReferenceRepository(Protocol):
    async def get_by_id(self, ref_id: int) -> Optional[Reference]: ...
    async def list_all(self, sort_by_recent: bool = False, user_id: int | None = None) -> builtins.list[Reference]: ...
    async def save(self, ref: Reference) -> Reference: ...
    async def is_referenced(self, ref_id: int) -> bool: ...
    async def reference_count(self, ref_id: int) -> int: ...
    async def delete(self, ref_id: int) -> None: ...


class TokenService(Protocol):
    def create_access_token(self, user_id: int) -> str: ...
    def create_refresh_token(self, user_id: int) -> str: ...
    def verify_token(self, token: str, expected_type: str) -> int: ...


class DocumentStorage(Protocol):
    async def save(self, filename: str, content: bytes, visit_date: datetime, procedure_id: Optional[int]) -> str: ...
    def get_path(self, relative_path: str) -> str: ...
